"""Golden numerical regression for omega retrieval.

Locks the numerical output of ``retrieve_omega_pixel_timeseries`` (8 temp_scheme ×
exp_mode cases, covering DH/SC/EXP2/EXP1A/EXP1B branches) and
``execute_omega_retrieval`` (matrix path) against a saved fixture. Any refactor
that changes the numerics will fail this test.

Coverage of nested closures (the extraction targets):
  * ``block_residual_function`` / ``evaluate_block_fit`` / ``solve_block_omega``
    are exercised by every case (main solve loop).
  * ``scan_exp2_lambda`` is exercised only by the EXP2 cases
    (``exp2.lambda_star`` finite).

Fixture: ``fixtures/omega_retrieval_golden.npz`` (generated by the current code
via .workbuddy/omega_golden_gen.py). If the algorithm is intentionally changed,
regenerate the fixture and document why.

Tolerance: rtol=1e-9 (tight enough to catch real regressions, loose enough for
cross-platform BLAS noise in scipy.optimize). NaN positions must match exactly.
"""

from __future__ import annotations

import unittest
from pathlib import Path

import numpy as np

from algorithms.omega import (
    OmegaConfig,
    OmegaFieldConfig,
    execute_omega_retrieval,
    retrieve_omega_pixel_timeseries,
)

_FIXTURE = Path(__file__).parent / "fixtures" / "omega_retrieval_golden.npz"
_RTOL = 1e-9
_ATOL = 1e-11


def _varied_pixel_kwargs(temp_scheme: str, exp_mode: str, nt: int = 12, **overrides):
    rng = np.random.default_rng(42)
    date_keys = [f"202512{i+1:02d}" for i in range(nt)]
    tbv = 255.0 + 8.0 * np.sin(np.linspace(0, 3 * np.pi, nt)) + rng.normal(0, 0.5, nt)
    tbh = 235.0 + 7.0 * np.cos(np.linspace(0, 3 * np.pi, nt)) + rng.normal(0, 0.5, nt)
    ts = 292.0 + 4.0 * np.sin(np.linspace(0, 2 * np.pi, nt) + 0.5)
    tc = 288.0 + 3.0 * np.cos(np.linspace(0, 2 * np.pi, nt)) if temp_scheme == "DUAL" else None
    tg = 285.0 + 3.0 * np.sin(np.linspace(0, 2 * np.pi, nt)) if temp_scheme == "DUAL" else None
    kw = {
        "date_keys": date_keys,
        "tbv": tbv, "tbh": tbh, "ts": ts, "tc": tc, "tg": tg,
        "ia": np.full(nt, 40.0),
        "sm_ref": np.full(nt, 0.2),
        "ndvi": np.full(nt, 0.4),
        "sf_col": np.full(nt, 1.0),
        "ndvi_max_value": 0.8, "ndvi_min_value": 0.1, "albedo_value": 0.1,
        "b_value": 0.1, "landcover_value": 10.0, "clay_fraction_value": 0.3,
        "bulk_density_value": 1.3, "h_static_value": 0.1,
        "fixed_omega_value": float("nan"),
        "exp0_h_value": float("nan"), "exp0_alpha_value": float("nan"),
        "config": OmegaConfig(temp_scheme=temp_scheme, exp_mode=exp_mode, block_days=8),
    }
    kw.update(overrides)
    return kw


# (key, temp_scheme, exp_mode, overrides)
_CASES = [
    ("ORIG_TS_DH", "ORIG_TS", "DH", {}),
    ("ORIG_TS_SC", "ORIG_TS", "SC", {}),
    ("DUAL_DH", "DUAL", "DH", {}),
    ("DUAL_SC", "DUAL", "SC", {}),
    ("ORIG_TS_EXP2", "ORIG_TS", "EXP2", {}),
    ("DUAL_EXP2", "DUAL", "EXP2", {}),
    ("ORIG_TS_EXP1B", "ORIG_TS", "EXP1B", {"fixed_omega_value": 0.1}),
    ("ORIG_TS_EXP1A", "ORIG_TS", "EXP1A",
     {"exp0_h_value": 0.9, "exp0_alpha_value": 0.11}),
]


class OmegaRetrievalGoldenTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.fix = dict(np.load(_FIXTURE, allow_pickle=False))

    def _assert_close(self, key: str, actual) -> None:
        self.assertIn(key, self.fix, f"missing fixture key {key!r}")
        exp = np.asarray(self.fix[key], dtype=np.float64)
        got = np.asarray(actual, dtype=np.float64)
        self.assertEqual(got.shape, exp.shape, f"{key}: shape {got.shape} != {exp.shape}")
        np.testing.assert_allclose(
            got, exp, rtol=_RTOL, atol=_ATOL, equal_nan=True, err_msg=f"{key}"
        )

    def test_pixel_cases_match_fixture(self) -> None:
        for key, ts_name, em, overrides in _CASES:
            with self.subTest(case=key):
                r = retrieve_omega_pixel_timeseries(
                    **_varied_pixel_kwargs(ts_name, em, **overrides)
                )
                for k in ("OMEGA", "SM_RET", "VOD_RET", "h_series", "alpha_series",
                          "TBv_mod", "TBh_mod", "rV", "rH", "low_tau", "valid_tau"):
                    self._assert_close(f"{key}.{k}", r[k])
                self._assert_close(f"{key}.h_star", r["h_star"])
                self._assert_close(f"{key}.alpha_star", r["alpha_star"])
                self._assert_close(f"{key}.n_use", r["n_use"])
                self._assert_close(f"{key}.n_low_tau", r["n_low_tau"])
                d = r["diag"]
                self._assert_close(f"{key}.diag.n_use", d["n_use"])
                self._assert_close(f"{key}.diag.exitflag", d["exitflag"])
                self._assert_close(f"{key}.diag.final_cost", d["final_cost"])
                self._assert_close(f"{key}.diag.iter", d["iter"])
                e2 = r["exp2"]
                self._assert_close(f"{key}.exp2.lambda_star", e2["lambda_star"])
                self._assert_close(f"{key}.exp2.misfit", e2["misfit"])
                self._assert_close(f"{key}.exp2.roughness", e2["roughness"])
                self._assert_close(f"{key}.exp2.rmse", e2["rmse"])

    def test_matrix_case_matches_fixture(self) -> None:
        nt, npix = 12, 6
        rng = np.random.default_rng(7)
        payload = {
            "date_keys": [f"202512{i+1:02d}" for i in range(nt)],
            "TBv_mat": 255.0 + 8.0 * np.sin(np.linspace(0, 3 * np.pi, nt))[:, None] + rng.normal(0, 0.5, (nt, npix)),
            "TBh_mat": 235.0 + 7.0 * np.cos(np.linspace(0, 3 * np.pi, nt))[:, None] + rng.normal(0, 0.5, (nt, npix)),
            "IA_mat": np.full((nt, npix), 40.0),
            "Ts_mat": (292.0 + 4.0 * np.sin(np.linspace(0, 2 * np.pi, nt) + 0.5))[:, None] * np.ones((1, npix)),
            "SMref_mat": np.full((nt, npix), 0.2),
            "NDVI_mat": np.full((nt, npix), 0.4),
            "SF_mat": np.full((nt, npix), 1.0),
            "Albedo": np.full(npix, 0.1), "B": np.full(npix, 0.1), "LC": np.full(npix, 10.0),
            "CF": np.full(npix, 0.3), "BD": np.full(npix, 1.3), "H": np.full(npix, 0.1),
            "NDVI_v_max": np.full(npix, 0.8), "NDVI_v_min": np.full(npix, 0.1),
        }
        e = execute_omega_retrieval(
            payload, config=OmegaConfig(temp_scheme="ORIG_TS", exp_mode="DH", block_days=8),
            field_config=OmegaFieldConfig(),
        )
        self._assert_close("mat.OMEGA_mat", e["OMEGA_mat"])
        self._assert_close("mat.SM_RET_mat", e["SM_RET_mat"])
        self._assert_close("mat.VOD_RET_mat", e["VOD_RET_mat"])
        self._assert_close("mat.h_star_vec", e["h_star_vec"])
        self._assert_close("mat.alpha_star_vec", e["alpha_star_vec"])


if __name__ == "__main__":
    unittest.main()
