/** 分析面板顶部摘要 / 角标 / 阶段文案 */

export const ANALYSIS_COPY = {
  panelTitle: '分析',
  subtitleEmpty: '开始分析',
  subtitleWeather: '天气图层',
  subtitleStatic: '图层摘要',
  subtitleWorkflow: '工作流',
  subtitleImportedVector: '导入矢量',
  subtitleImportedRaster: '导入栅格',
  subtitleBoundary: '行政区边界',

  stageEmpty: '待选图层',
  stageWeather: '天气图层',
  stageLocal: '本地图层',
  stageImportedVector: '导入矢量',
  stageImportedRaster: '导入栅格',
  stageBoundary: '边界图层',
  stageWorkflow: '分析工作流',
  stageStatic: '静态图层',

  emptyTitle: '尚未选中图层',
  emptyLead: '从左侧图层面板添加数据图层后，可在此查看摘要、点查与样式。',
  emptyLeadShort: '添加或选中图层后，图表、工具与样式会显示在这里。',
  emptyStepAdd: '在左侧添加或选中一个图层',
  emptyStepInspect: '天气层可点查地图取值',
  emptyStepStyle: '样式与透明度在「样式」中调节',
  emptyHintInspect: '添加天气层后，可用工具栏「选择」点击地图点查。',
  emptyHintWind: '风场层支持粒子流 / 流量场显示切换。',

  sparseVisualTitle: '暂无图表',
  sparseVisualWeather: '平移地图加载瓦片，或进入点查查看数值。',
  sparseVisualWorkflow: '工作流产出图表与表格将显示在此；可从侧栏右键或工作流编辑器提交运行。',
  sparseVisualStatic: '当前图层无可视化图表；可在样式中调节外观，或在工具中点选缓冲。',
  sparseToolsHint: '进入选择模式并在地图上点选后，可估算缓冲覆盖。',

  overviewImportedVector: (geometry: string, count: number) =>
    `本地导入矢量 · ${geometry} · ${count} 个要素`,
  overviewImportedRaster: '本地导入栅格（GeoTIFF），已叠加到地图。',
  overviewBoundary: '行政区矢量边界仅作空间参考，不作为分析数据集。',
  importedSectionKicker: '导入',
  importedSectionTitle: '本地数据',
  importedRasterType: '栅格 · GeoTIFF 叠加层',
  metaNativeStep: '原生时间步',
  metaEffectiveTime: '生效时间区间',
  metaTimeSlices: '可用时刻/块',
  selectedLayerKicker: '当前对象',
  selectedLayerTitle: '选中图层',
  overviewKicker: '总览',
  overviewTitleCompact: '图层说明',
  overviewTitleFull: '全图态势',

  weatherAutoLoad: '瓦片按视口自动加载，无需手动提交工作流。',
  weatherTileLine: (cached: number, visible: number, pending: number) =>
    `瓦片：已缓存 ${cached} / 可视 ${visible} / 加载中 ${pending}`,
  weatherNoTilesYet: '尚未缓存瓦片，平移或缩放地图以加载当前视口。',
  weatherWindMode: (modeLabel: string) => `风场显示：${modeLabel}`,

  staticImported: '本地导入图层：支持样式调节、属性查询与导出。',
  staticImportedVector: '导入矢量：可调颜色、线宽、点半径与透明度，支持属性表操作。',
  staticImportedRaster: '导入栅格：支持图例预览、透明度调节与元数据展示。',
  staticBoundary: '行政区边界：空间轮廓参考（非课题数据集）。',
  staticOverlay: '该图层为叠加图层，已就绪显示。',

  styleTitle: '图层样式',
  styleHintLinked: '图例与配色与地图符号化联动。',
  styleHintReadonly: '预渲染图例仅作对照，改配色不会重涂已生成的 PNG。',
  styleHintOpacityOnly: '该图层无可调符号配置，可调节地图透明度。',
  styleSectionKicker: '符号',
  styleTabEmpty: '选中图层后可调节样式。',
  visualTabEmpty: '暂无图表内容。',
  toolsQuickBuffer: '缓冲 / 点选',
  toolsQuickInspect: '进入点查',

  metaLayer: '图层',
  metaSource: '来源',
  metaTime: '时间',
  metaMode: '显示',
  metaCrs: '坐标系',
  metaBounds: '范围',
  metaFeatures: '要素数',
  metaGeometry: '几何类型',
  metaWorkflow: '工作流来源',
  metaFile: '源文件',

  stageIdleReady: '就绪',
  stageIdleNotRun: '尚未运行',
  stageDone: '完成',
  stageFailed: '失败',
  stageLoading: '加载中',
  stageCached: '已缓存',
} as const
