/** 工具栏「数据」导入/导出文案 */
export const DATA_COPY = {
  menuLabel: '数据',
  menuTitle: '数据工作台：导入 / 导出 / 属性 / 详情',
  import: '导入',
  export: '导出',
  importTitle: '数据导入',
  exportTitle: '数据导出',
  workspaceTitle: '数据工作台',
  workspaceSub: '导入 · 导出 · 属性 · 详情 · 作业',
  wsImport: '导入',
  wsExport: '导出',
  wsAttributes: '属性表',
  wsDetails: '详情',
  wsJobs: '作业',
  jobsHint: '批导入 / 大文件异步 / 批导出任务',
  jobsRefresh: '刷新',
  jobsEmpty: '暂无近期作业',
  jobsCancel: '取消',
  maximize: '全屏',
  tabVector: '矢量',
  tabRaster: '栅格',
  tabDocument: '文档',
  vectorHint: '支持 .shp（须同时选中 .dbf/.shx）/ .zip / .geojson；可一次选多个独立数据集',
  rasterHint:
    '支持 .tif / .nc / .hdf / .h5 / .mat；科学格式可配置变量、网格（WGS84 / EASE-Grid 2.0 9km 等）、范围与无效值后再导入（可多变量→多层）',
  documentHint: '支持 .csv / .xlsx / .xls / .txt；可多选排队，筛选/替换/分列后导入为点',
  exportHint:
    '可多选已导入/工作流产出图层；矢量 GeoJSON/CSV/SHP，栅格优先原生 GeoTIFF / MAT（含 lat/lon）。支持裁剪地图范围、输出 CRS、字段勾选；多选同网格 MAT 合并为多变量单文件',
  exportTime: '导出时刻 / 块',
  exportTimeHint: '单时刻写入文件名；多时刻打包为 zip（如 layer_20251203_20251231.zip）',
  exportTimeModeSingle: '单时刻',
  exportTimeModeMulti: '多时刻打包 (zip)',
  exportTimeSelectAll: '全选时刻',
  exportTimeClear: '清空时刻',
  exportTimeCommon: '多选公共时刻',
  exportEncoding: '文本编码',
  exportEncodingHint:
    'auto=跟导入源编码；国内 ArcGIS 常用 GBK；Excel 推荐 UTF-8 BOM；GeoJSON 始终 UTF-8',
  exportClipMap: '裁剪到当前地图范围',
  exportOutputCrs: '输出坐标系',
  exportOutputCrsSource: '保持源 CRS',
  exportFields: '矢量属性字段',
  exportFieldsAll: '全选字段',
  exportFieldsClear: '清空字段',
  exportFieldsHint: '不勾选则导出全部属性；CSV/SHP/GeoJSON 均生效',
  exportMachineId: '导出用 id',
  exportWorkflowProduct: '工作流产出',
  exportLoadFullFirst: '正在加载完整矢量数据…',
  exportRasterGeotiff: 'GeoTIFF（原生）',
  exportRasterNc: 'NetCDF',
  exportRasterMat: 'MAT（多变量 + lat/lon）',
  exportRasterPng: '预览 PNG',
  attrEncodingUnknown: '源编码未记录（GeoJSON/文档导入）',
  attrCopyCell: '复制单元格',
  attrCopySelected: '复制选中行',
  attrSelectPage: '全选本页',
  attrClearSel: '清除选中',
  attrCopied: '已复制到剪贴板',
  attrCopyFail: '复制失败',
  attrHintMulti: '单击选中 · Ctrl/⌘ 多选 · Shift 范围 · 双击编辑',
  close: '关闭',
  upload: '选择文件',
  uploading: '上传中…',
  processing: '处理中…',
  cancelUpload: '取消上传',
  commit: '确认导入',
  batchImport: '开始批量导入',
  applyOps: '应用操作',
  emptyExport: '暂无已导入图层可导出',
  vectorSidecarTip:
    '重要：请用 Ctrl 同时选中同名的 .shp + .dbf + .shx（.prj 可选），或打成一个 .zip 再导入。浏览器只会上传您选中的文件，不会自动带上磁盘同目录里未选中的附属文件。',
  pickVariable: '选择变量 / 数据集',
  timeIndex: '时间索引',
  xField: 'X / 经度列',
  yField: 'Y / 纬度列',
  sourceCrs: '源坐标系',
  renameFrom: '原字段名',
  renameTo: '新字段名',
  filterField: '筛选字段',
  filterContains: '包含',
  attrWhere: '条件',
  attrWherePh: 'field=value; score>10',
  attrZoomSelected: '缩放到选中',
  attrAddField: '新字段',
  attrAddFieldBtn: '添加字段',
  attrDeleteField: '删除字段',
  attrBatchField: '批量字段',
  attrBatchValue: '批量值',
  attrBatchSet: '批量赋值',
  attrSelected: '已选',
  findReplaceField: '字段',
  findText: '查找',
  replaceText: '替换为',
  splitField: '分列字段',
  splitSep: '分隔符',
  splitInto: '新列名（逗号分隔）',
  exportFormat: '导出格式',
  doExport: '开始导出',
  selectAll: '全选',
  clearSelection: '清空',
  attrLayer: '图层',
  attrEmpty: '暂无已导入矢量图层',
  attrFilter: '筛选',
  attrRename: '重命名字段',
  attrPrev: '上一页',
  attrNext: '下一页',
  attrRows: '行',
  detailsMeta: '元数据',
  detailsStyle: '矢量样式',
  detailsActions: '操作',
  applyStyle: '应用样式',
  styleApplied: '样式已应用到地图',
  openAttributes: '打开属性表',
  loadFull: '加载完整数据到地图',
  deleteLayer: '删除图层',
  layerRemoved: '图层已移除',
  openWorkspace: '打开工作台',
  openDetails: '图层详情',
  openAttrTable: '属性表',
} as const
