/** 图层侧栏空态 / 右键菜单 / 符号化 */
export const LAYERS_COPY = {
  emptyTitle: '暂无图层',
  emptyActive: '暂无已添加图层',
  emptyActiveCta: '去图层库添加',
  noDataSource: '暂无可用数据源',
  pleaseSelectSource: '请选择数据源',
  footerActive: '拖动排序 · 双击缩放 · 右键更多操作与符号化',
  symbology: '符号化',
  opacity: '透明度',
  zoomToExtent: '缩放到图层',
  viewDetails: '查看详情',
  toggleVisible: '显示 / 隐藏',
  showLayer: '显示图层',
  hideLayer: '隐藏图层',
  bringToFront: '置于顶层',
  sendToBack: '置于底层',
  rename: '重命名',
  renamePrompt: '图层显示名称',
  openAttributes: '属性表',
  openStyle: '样式…',
  openDetails: '详情',
  exportGeoJson: '导出 GeoJSON',
  exportCsv: '导出 CSV',
  exportPng: '导出 PNG',
  exportTif: '导出 GeoTIFF',
  runWorkflow: '运行工作流',
  viewReport: '查看报告',
  removeLayer: '移除图层',
  groupView: '查看',
  groupAppearance: '外观',
  groupOrder: '顺序',
  groupData: '数据',
  groupWorkflow: '工作流',
  groupDanger: '危险',
  fieldLabel: '字段',
  paletteLabel: '配色',
  paletteHintReadonly: '预渲染图例，不支持前端改色',
  paletteTitleEdit: '切换地图配色',
  paletteTitleReadonly: '预渲染栅格图例，改配色不会重涂 PNG',
  openInAnalysis: '在分析面板打开',
  sectionAppearance: '外观',
  sectionRange: '数值范围',
  sectionSource: '数据来源',
  metricCrs: '坐标系',
  metricBounds: '范围',
  metricSourceFile: '源文件',
  metricFeatures: '要素数',
  metricGeometry: '几何类型',
  metricUnit: '单位',
  vectorColor: '颜色',
  vectorWidth: '线宽',
  vectorRadius: '点半径',
  vectorFillOpacity: '填充透明度',
} as const
