from __future__ import annotations

SCHEMA_VERSION_1_0 = "1.0"
SCHEMA_VERSION_1_1 = "1.1"
SCHEMA_VERSION_1_2 = "1.2"
SCHEMA_VERSION_1_3 = "1.3"
SCHEMA_VERSION_1_4 = "1.4"
SCHEMA_VERSION_1_5 = "1.5"
SCHEMA_VERSION_1_6 = "1.6"
SCHEMA_VERSION_1_7 = "1.7"
SCHEMA_VERSION_1_8 = "1.8"
SCHEMA_VERSION_1_9 = "1.9"
SCHEMA_VERSION_1_10 = "1.10"
SCHEMA_VERSION_1_11 = "1.11"
SCHEMA_VERSION_1_12 = "1.12"
CURRENT_SCHEMA_VERSION = SCHEMA_VERSION_1_12
LEGACY_SCHEMA_VERSION = "legacy"
SUPPORTED_SCHEMA_VERSIONS = (CURRENT_SCHEMA_VERSION,)
SCHEMA_UPGRADE_PATHS = {
    LEGACY_SCHEMA_VERSION: (
        SCHEMA_VERSION_1_0,
        SCHEMA_VERSION_1_1,
        SCHEMA_VERSION_1_2,
        SCHEMA_VERSION_1_3,
        SCHEMA_VERSION_1_4,
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_0: (
        SCHEMA_VERSION_1_1,
        SCHEMA_VERSION_1_2,
        SCHEMA_VERSION_1_3,
        SCHEMA_VERSION_1_4,
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_1: (
        SCHEMA_VERSION_1_2,
        SCHEMA_VERSION_1_3,
        SCHEMA_VERSION_1_4,
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_2: (
        SCHEMA_VERSION_1_3,
        SCHEMA_VERSION_1_4,
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_3: (
        SCHEMA_VERSION_1_4,
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_4: (
        SCHEMA_VERSION_1_5,
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_5: (
        SCHEMA_VERSION_1_6,
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_6: (
        SCHEMA_VERSION_1_7,
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_7: (
        SCHEMA_VERSION_1_8,
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_8: (
        SCHEMA_VERSION_1_9,
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_9: (
        SCHEMA_VERSION_1_10,
        SCHEMA_VERSION_1_11,
        CURRENT_SCHEMA_VERSION,
    ),
    SCHEMA_VERSION_1_10: (SCHEMA_VERSION_1_11, CURRENT_SCHEMA_VERSION),
    SCHEMA_VERSION_1_11: (CURRENT_SCHEMA_VERSION,),
}
AUTO_MIGRATE_FROM_SCHEMA_VERSIONS = tuple(SCHEMA_UPGRADE_PATHS.keys())
