import type { LayerCatalogItem, LayerCategory, LayerSource } from './types'

export const LAYER_CATEGORIES: LayerCategory[] = [
  {
    id: 'meteorology',
    name: '气象场',
    icon: 'M',
    accentColor: '#67d4ff',
    chipTone: 'rgba(103, 212, 255, 0.18)',
  },
  {
    id: 'disaster',
    name: '灾害监测',
    icon: 'D',
    accentColor: '#72ffcf',
    chipTone: 'rgba(114, 255, 207, 0.16)',
  },
  {
    id: 'thermal',
    name: '热环境',
    icon: 'T',
    accentColor: '#ffb65c',
    chipTone: 'rgba(255, 182, 92, 0.16)',
  },
  {
    id: 'atmosphere',
    name: '大气环境',
    icon: 'A',
    accentColor: '#c9a3ff',
    chipTone: 'rgba(201, 163, 255, 0.16)',
  },
  {
    id: 'remote-sensing',
    name: '遥感产品',
    icon: 'R',
    accentColor: '#bb89ff',
    chipTone: 'rgba(187, 137, 255, 0.16)',
  },
  {
    id: 'vegetation',
    name: '植被监测',
    icon: 'V',
    accentColor: '#7fd99a',
    chipTone: 'rgba(127, 217, 154, 0.16)',
  },
  {
    id: 'runtime',
    name: '运行时目录',
    icon: 'C',
    accentColor: '#7ea7ff',
    chipTone: 'rgba(126, 167, 255, 0.16)',
  },
  {
    id: 'boundary',
    name: '行政边界',
    icon: 'B',
    accentColor: '#88d8ff',
    chipTone: 'rgba(136, 216, 255, 0.16)',
  },
]

// ── 数据源定义 ──────────────────────────────────────────────────────────────
// 命名约定：每个 source.name 唯一且具备可识别性，避免不同图层共用同名数据源导致冲突。

const SOURCE_WEATHERENGINE_WIND: LayerSource = {
  id: 'weatherengine-wind',
  name: 'Open-Meteo 风场（多模型）',
  description: '由后端 weatherengine 路由的 Open-Meteo 站点风场数据，支持多模型选择。',
  urlTemplate: 'https://example.com/wind/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_80M: LayerSource = {
  id: 'weatherengine-wind-80m',
  name: 'Open-Meteo 80m 风场',
  description: 'Open-Meteo 80 米高度风场数据，对应现代风机轮毂高度。',
  urlTemplate: 'https://example.com/wind-80m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_120M: LayerSource = {
  id: 'weatherengine-wind-120m',
  name: 'Open-Meteo 120m 风场',
  description: 'Open-Meteo 120 米高度风场数据，大型/海上风机轮毂高度参考层。',
  urlTemplate: 'https://example.com/wind-120m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_180M: LayerSource = {
  id: 'weatherengine-wind-180m',
  name: 'Open-Meteo 180m 风场',
  description: 'Open-Meteo 180 米高度风场数据，大气边界层顶部参考风场。',
  urlTemplate: 'https://example.com/wind-180m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_850HPA: LayerSource = {
  id: 'weatherengine-wind-850hPa',
  name: 'Open-Meteo 850hPa 风场',
  description: 'Open-Meteo 850 hPa 气压层风场数据（约 1.5 km AGL），低空急流与对流 inflow 参考。',
  urlTemplate: 'https://example.com/wind-850hpa/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_500HPA: LayerSource = {
  id: 'weatherengine-wind-500hPa',
  name: 'Open-Meteo 500hPa 风场',
  description: 'Open-Meteo 500 hPa 气压层风场数据（约 5.5 km AGL），中空天气尺度流场参考。',
  urlTemplate: 'https://example.com/wind-500hpa/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_WIND_200HPA: LayerSource = {
  id: 'weatherengine-wind-200hPa',
  name: 'Open-Meteo 200hPa 风场',
  description: 'Open-Meteo 200 hPa 气压层风场数据（约 12 km AGL），高空急流参考层。',
  urlTemplate: 'https://example.com/wind-200hpa/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_PRECIP: LayerSource = {
  id: 'weatherengine-precipitation',
  name: 'Open-Meteo 降水量',
  description: '由后端 weatherengine 路由的 Open-Meteo 站点降水量数据。',
  urlTemplate: 'https://example.com/precip/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_TEMP: LayerSource = {
  id: 'weatherengine-temperature',
  name: 'Open-Meteo 温度',
  description: '由后端 weatherengine 路由的 Open-Meteo 站点温度数据。',
  urlTemplate: 'https://example.com/temperature/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_TEMP_80M: LayerSource = {
  id: 'weatherengine-temperature-80m',
  name: 'Open-Meteo 80m 温度',
  description: 'Open-Meteo 80 米高度温度数据，适用于风机结冰与尾流分析。',
  urlTemplate: 'https://example.com/temperature-80m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_TEMP_120M: LayerSource = {
  id: 'weatherengine-temperature-120m',
  name: 'Open-Meteo 120m 温度',
  description: 'Open-Meteo 120 米高度温度数据，大型风机轮毂高度热力参考。',
  urlTemplate: 'https://example.com/temperature-120m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_TEMP_180M: LayerSource = {
  id: 'weatherengine-temperature-180m',
  name: 'Open-Meteo 180m 温度',
  description: 'Open-Meteo 180 米高度温度数据，大气边界层顶部热力剖面。',
  urlTemplate: 'https://example.com/temperature-180m/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_PRESSURE: LayerSource = {
  id: 'weatherengine-pressure',
  name: 'Open-Meteo 海平面气压',
  description: '由后端 weatherengine 路由的 Open-Meteo 海平面气压数据。',
  urlTemplate: 'https://example.com/pressure/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_HUMIDITY: LayerSource = {
  id: 'weatherengine-humidity',
  name: 'Open-Meteo 相对湿度',
  description: '由后端 weatherengine 路由的 Open-Meteo 近地面相对湿度数据。',
  urlTemplate: 'https://example.com/humidity/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_WEATHERENGINE_VISIBILITY: LayerSource = {
  id: 'weatherengine-visibility',
  name: 'Open-Meteo 能见度',
  description: '由后端 weatherengine 路由的 Open-Meteo 地面能见度数据。',
  urlTemplate: 'https://example.com/visibility/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: '每小时更新',
}

const SOURCE_NDVI: LayerSource = {
  id: 'ndvi-satellite',
  name: 'Landsat / Sentinel-2 NDVI 产品',
  description: '由 Landsat 8/9 与 Sentinel-2 红/近红外波段反演的 NDVI 产品。',
  urlTemplate: 'https://example.com/ndvi/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: '每日更新',
}

const SOURCE_LANDSAT: LayerSource = {
  id: 'landsat-sentinel',
  name: 'Landsat / Sentinel 综合遥感产品',
  description: '基于 Landsat 8/9 与 Sentinel-2 的多波段反演产品（不含 NDVI）。',
  urlTemplate: 'https://example.com/rs/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: '每日更新',
}

const SOURCE_LAB: LayerSource = {
  id: 'lab-model',
  name: '课题组工作流输出',
  description: '由后端工作流任务生成的结果产物。',
  urlTemplate: '',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: '按工作流运行',
}

const SOURCE_GD_BOUNDARY: LayerSource = {
  id: 'guangdong-admin',
  name: '广东省市级行政边界',
  description: '广东省市级行政区边界矢量数据（GeoJSON）。',
  urlTemplate: '',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: '静态数据',
}

export const LAYER_LIBRARY: LayerCatalogItem[] = [
  {
    catalogId: 'wind-field',
    name: '风场（10m）',
    category: 'meteorology',
    metricLabel: '风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#67d4ff',
    accentGlow: 'rgba(103, 212, 255, 0.34)',
    chipTone: 'rgba(103, 212, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND],
  },
  {
    catalogId: 'wind-field-80m',
    name: '风场（80m）',
    category: 'meteorology',
    metricLabel: '风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#7ec4ff',
    accentGlow: 'rgba(126, 196, 255, 0.34)',
    chipTone: 'rgba(126, 196, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_80M],
  },
  {
    catalogId: 'wind-field-120m',
    name: '风场（120m）',
    category: 'meteorology',
    metricLabel: '风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#95b8ff',
    accentGlow: 'rgba(149, 184, 255, 0.34)',
    chipTone: 'rgba(149, 184, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_120M],
  },
  {
    catalogId: 'wind-field-180m',
    name: '风场（180m）',
    category: 'meteorology',
    metricLabel: '风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#a8a8ff',
    accentGlow: 'rgba(168, 168, 255, 0.34)',
    chipTone: 'rgba(168, 168, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_180M],
  },
  {
    catalogId: 'wind-field-850hPa',
    name: '风场（850hPa）',
    category: 'meteorology',
    metricLabel: '850hPa 风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#8fb8ff',
    accentGlow: 'rgba(143, 184, 255, 0.34)',
    chipTone: 'rgba(143, 184, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_850HPA],
  },
  {
    catalogId: 'wind-field-500hPa',
    name: '风场（500hPa）',
    category: 'meteorology',
    metricLabel: '500hPa 风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#7ea0ff',
    accentGlow: 'rgba(126, 160, 255, 0.34)',
    chipTone: 'rgba(126, 160, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_500HPA],
  },
  {
    catalogId: 'wind-field-200hPa',
    name: '风场（200hPa）',
    category: 'meteorology',
    metricLabel: '200hPa 风速',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#6e88ff',
    accentGlow: 'rgba(110, 136, 255, 0.34)',
    chipTone: 'rgba(110, 136, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND_200HPA],
  },
  {
    catalogId: 'precipitation',
    name: '降水',
    category: 'disaster',
    metricLabel: '峰值降水',
    metricUnit: 'mm/h',
    metricPrecision: 0,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#72ffcf',
    accentGlow: 'rgba(114, 255, 207, 0.3)',
    chipTone: 'rgba(114, 255, 207, 0.16)',
    sources: [SOURCE_WEATHERENGINE_PRECIP],
  },
  {
    catalogId: 'temperature',
    name: '温度',
    category: 'thermal',
    metricLabel: '区域均温',
    metricUnit: '°C',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#ffb65c',
    accentGlow: 'rgba(255, 182, 92, 0.3)',
    chipTone: 'rgba(255, 182, 92, 0.16)',
    sources: [SOURCE_WEATHERENGINE_TEMP],
  },
  {
    catalogId: 'temperature-80m',
    name: '温度（80m）',
    category: 'thermal',
    metricLabel: '80m 温度',
    metricUnit: '°C',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#ffc97a',
    accentGlow: 'rgba(255, 201, 122, 0.3)',
    chipTone: 'rgba(255, 201, 122, 0.16)',
    sources: [SOURCE_WEATHERENGINE_TEMP_80M],
  },
  {
    catalogId: 'temperature-120m',
    name: '温度（120m）',
    category: 'thermal',
    metricLabel: '120m 温度',
    metricUnit: '°C',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#ffdc8a',
    accentGlow: 'rgba(255, 220, 138, 0.3)',
    chipTone: 'rgba(255, 220, 138, 0.16)',
    sources: [SOURCE_WEATHERENGINE_TEMP_120M],
  },
  {
    catalogId: 'temperature-180m',
    name: '温度（180m）',
    category: 'thermal',
    metricLabel: '180m 温度',
    metricUnit: '°C',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#ffe49a',
    accentGlow: 'rgba(255, 228, 154, 0.3)',
    chipTone: 'rgba(255, 228, 154, 0.16)',
    sources: [SOURCE_WEATHERENGINE_TEMP_180M],
  },
  {
    catalogId: 'pressure',
    name: '气压',
    category: 'atmosphere',
    metricLabel: '海平面气压',
    metricUnit: 'hPa',
    metricPrecision: 1,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#c9a3ff',
    accentGlow: 'rgba(201, 163, 255, 0.3)',
    chipTone: 'rgba(201, 163, 255, 0.16)',
    sources: [SOURCE_WEATHERENGINE_PRESSURE],
  },
  {
    catalogId: 'humidity',
    name: '湿度',
    category: 'atmosphere',
    metricLabel: '相对湿度',
    metricUnit: '%',
    metricPrecision: 0,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#a3d9b0',
    accentGlow: 'rgba(163, 217, 176, 0.3)',
    chipTone: 'rgba(163, 217, 176, 0.16)',
    sources: [SOURCE_WEATHERENGINE_HUMIDITY],
  },
  {
    catalogId: 'visibility',
    name: '能见度',
    category: 'atmosphere',
    metricLabel: '能见度',
    metricUnit: 'm',
    metricPrecision: 0,
    updateLabel: '每小时更新',
    sourceLabel: 'Open-Meteo · weatherengine',
    accentColor: '#e8c87a',
    accentGlow: 'rgba(232, 200, 122, 0.3)',
    chipTone: 'rgba(232, 200, 122, 0.16)',
    sources: [SOURCE_WEATHERENGINE_VISIBILITY],
  },
  {
    catalogId: 'ndvi',
    name: '植被指数（NDVI）',
    category: 'vegetation',
    metricLabel: '植被指数',
    metricUnit: '',
    metricPrecision: 2,
    updateLabel: '每日更新',
    sourceLabel: 'Landsat / Sentinel-2',
    accentColor: '#7fd99a',
    accentGlow: 'rgba(127, 217, 154, 0.3)',
    chipTone: 'rgba(127, 217, 154, 0.16)',
    sources: [SOURCE_NDVI],
  },
  {
    catalogId: 'remote-sensing',
    name: '遥感反演产品',
    category: 'remote-sensing',
    metricLabel: '反演指数',
    metricUnit: '',
    metricPrecision: 2,
    updateLabel: '每日更新',
    sourceLabel: 'Landsat / Sentinel',
    accentColor: '#bb89ff',
    accentGlow: 'rgba(187, 137, 255, 0.3)',
    chipTone: 'rgba(187, 137, 255, 0.16)',
    sources: [SOURCE_LANDSAT],
  },
  {
    catalogId: 'lab-output',
    name: '课题组模型输出',
    category: 'runtime',
    metricLabel: '综合评分',
    metricUnit: '/ 100',
    metricPrecision: 0,
    updateLabel: '按工作流运行',
    sourceLabel: '工作流任务输出',
    accentColor: '#ff6f91',
    accentGlow: 'rgba(255, 111, 145, 0.3)',
    chipTone: 'rgba(255, 111, 145, 0.16)',
    sources: [SOURCE_LAB],
  },
  {
    catalogId: 'smap-soil',
    name: 'SMAP 土壤湿度',
    category: 'thermal',
    metricLabel: '土壤湿度',
    metricUnit: 'm³/m³',
    metricPrecision: 3,
    updateLabel: '每日更新',
    sourceLabel: 'NASA SMAP',
    accentColor: '#a8e6a3',
    accentGlow: 'rgba(168, 230, 163, 0.3)',
    chipTone: 'rgba(168, 230, 163, 0.16)',
    sources: [],
  },
  {
    catalogId: 'admin-boundary',
    name: '行政区边界',
    category: 'boundary',
    metricLabel: '边界层级',
    metricUnit: '',
    metricPrecision: 0,
    updateLabel: '静态数据',
    sourceLabel: '广东省市级行政边界',
    accentColor: '#88d8ff',
    accentGlow: 'rgba(136, 216, 255, 0.3)',
    chipTone: 'rgba(136, 216, 255, 0.16)',
    sources: [SOURCE_GD_BOUNDARY],
    isAdminBoundary: true,
  },
]

export const LAYER_LIBRARY_BY_CATEGORY = (() => {
  const map = new Map<string, LayerCatalogItem[]>()
  for (const item of LAYER_LIBRARY) {
    if (!map.has(item.category)) {
      map.set(item.category, [])
    }
    map.get(item.category)!.push(item)
  }
  return map
})()
