import type { LayerCatalogItem, LayerCategory, LayerSource } from './types'

export const LAYER_CATEGORIES: LayerCategory[] = [
  {
    id: 'meteorology',
    name: 'Meteorology',
    icon: 'M',
    accentColor: '#67d4ff',
    chipTone: 'rgba(103, 212, 255, 0.18)',
  },
  {
    id: 'disaster',
    name: 'Disaster',
    icon: 'D',
    accentColor: '#72ffcf',
    chipTone: 'rgba(114, 255, 207, 0.16)',
  },
  {
    id: 'thermal',
    name: 'Thermal',
    icon: 'T',
    accentColor: '#ffb65c',
    chipTone: 'rgba(255, 182, 92, 0.16)',
  },
  {
    id: 'remote-sensing',
    name: 'Remote Sensing',
    icon: 'R',
    accentColor: '#bb89ff',
    chipTone: 'rgba(187, 137, 255, 0.16)',
  },
  {
    id: 'simulation',
    name: 'Simulation',
    icon: 'S',
    accentColor: '#ff6f91',
    chipTone: 'rgba(255, 111, 145, 0.16)',
  },
  {
    id: 'boundary',
    name: 'Boundary',
    icon: 'B',
    accentColor: '#88d8ff',
    chipTone: 'rgba(136, 216, 255, 0.16)',
  },
]

const SOURCE_WEATHERENGINE_WIND: LayerSource = {
  id: 'weatherengine-wind',
  name: 'Open-Meteo / Multi-model',
  description: 'Open-Meteo point weather routed through backend weatherengine with model selection support.',
  urlTemplate: 'https://example.com/wind/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Hourly refresh',
}

const SOURCE_WEATHERENGINE_PRECIP: LayerSource = {
  id: 'weatherengine-precipitation',
  name: 'Open-Meteo / Precipitation',
  description: 'Open-Meteo point precipitation accessed via backend weatherengine.',
  urlTemplate: 'https://example.com/precip/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Hourly refresh',
}

const SOURCE_WEATHERENGINE_TEMP: LayerSource = {
  id: 'weatherengine-temperature',
  name: 'Open-Meteo / Temperature',
  description: 'Open-Meteo point temperature accessed via backend weatherengine.',
  urlTemplate: 'https://example.com/temperature/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: true,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Hourly refresh',
}

const SOURCE_LANDSAT: LayerSource = {
  id: 'landsat-sentinel',
  name: 'Landsat / Sentinel',
  description: 'Landsat 8/9 and Sentinel-2 derived products.',
  urlTemplate: 'https://example.com/rs/{z}/{x}/{y}.png',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Daily refresh',
}

const SOURCE_LAB: LayerSource = {
  id: 'lab-model',
  name: 'Workflow Output',
  description: 'Task outputs generated by backend workflow jobs.',
  urlTemplate: '',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Per workflow run',
}

const SOURCE_GD_BOUNDARY: LayerSource = {
  id: 'guangdong-admin',
  name: 'Guangdong Admin Boundary',
  description: 'Guangdong city-level administrative boundary GeoJSON.',
  urlTemplate: '',
  needsAuth: false,
  needsBackendTransform: false,
  coordSys: 'EPSG:3857',
  updateFrequency: 'Static',
}

export const LAYER_LIBRARY: LayerCatalogItem[] = [
  {
    catalogId: 'wind-field',
    name: 'Wind Field',
    category: 'meteorology',
    metricLabel: 'Core Metric',
    metricUnit: 'm/s',
    metricPrecision: 1,
    updateLabel: 'Hourly refresh',
    sourceLabel: 'Open-Meteo / weatherengine',
    accentColor: '#67d4ff',
    accentGlow: 'rgba(103, 212, 255, 0.34)',
    chipTone: 'rgba(103, 212, 255, 0.18)',
    sources: [SOURCE_WEATHERENGINE_WIND],
  },
  {
    catalogId: 'precipitation',
    name: 'Precipitation',
    category: 'disaster',
    metricLabel: 'Peak Precipitation',
    metricUnit: 'mm/h',
    metricPrecision: 0,
    updateLabel: 'Hourly refresh',
    sourceLabel: 'Open-Meteo / weatherengine',
    accentColor: '#72ffcf',
    accentGlow: 'rgba(114, 255, 207, 0.3)',
    chipTone: 'rgba(114, 255, 207, 0.16)',
    sources: [SOURCE_WEATHERENGINE_PRECIP],
  },
  {
    catalogId: 'temperature',
    name: 'Temperature',
    category: 'thermal',
    metricLabel: 'Regional Temperature',
    metricUnit: 'C',
    metricPrecision: 1,
    updateLabel: 'Hourly refresh',
    sourceLabel: 'Open-Meteo / weatherengine',
    accentColor: '#ffb65c',
    accentGlow: 'rgba(255, 182, 92, 0.3)',
    chipTone: 'rgba(255, 182, 92, 0.16)',
    sources: [SOURCE_WEATHERENGINE_TEMP],
  },
  {
    catalogId: 'remote-sensing',
    name: 'Remote Sensing',
    category: 'remote-sensing',
    metricLabel: 'Retrieval Index',
    metricUnit: '',
    metricPrecision: 2,
    updateLabel: 'Daily refresh',
    sourceLabel: 'Landsat / Sentinel',
    accentColor: '#bb89ff',
    accentGlow: 'rgba(187, 137, 255, 0.3)',
    chipTone: 'rgba(187, 137, 255, 0.16)',
    sources: [SOURCE_LANDSAT],
  },
  {
    catalogId: 'lab-output',
    name: 'Lab Output',
    category: 'simulation',
    metricLabel: 'Composite Score',
    metricUnit: '/ 100',
    metricPrecision: 0,
    updateLabel: 'Per workflow run',
    sourceLabel: 'Workflow Output',
    accentColor: '#ff6f91',
    accentGlow: 'rgba(255, 111, 145, 0.3)',
    chipTone: 'rgba(255, 111, 145, 0.16)',
    sources: [SOURCE_LAB],
  },
  {
    catalogId: 'smap-soil',
    name: 'SMAP Soil Moisture',
    category: 'thermal',
    metricLabel: 'Soil Moisture',
    metricUnit: 'm3/m3',
    metricPrecision: 3,
    updateLabel: 'Daily refresh',
    sourceLabel: 'NASA SMAP',
    accentColor: '#a8e6a3',
    accentGlow: 'rgba(168, 230, 163, 0.3)',
    chipTone: 'rgba(168, 230, 163, 0.16)',
    sources: [],
  },
  {
    catalogId: 'admin-boundary',
    name: 'Administrative Boundary',
    category: 'boundary',
    metricLabel: 'Boundary Level',
    metricUnit: '',
    metricPrecision: 0,
    updateLabel: 'Static',
    sourceLabel: 'Guangdong Admin Boundary',
    accentColor: '#88d8ff',
    accentGlow: 'rgba(136, 216, 255, 0.3)',
    chipTone: 'rgba(136, 216, 255, 0.16)',
    sources: [SOURCE_GD_BOUNDARY],
    isAdminBoundary: true,
  },
]

export const LAYER_LIBRARY_BY_CATEGORY = (() => {
  const map = new Map<string, LayerCatalogItem[]>()
  for (const item of LAYER_LIBRARY) {
    if (!map.has(item.category)) {
      map.set(item.category, [])
    }
    map.get(item.category)!.push(item)
  }
  return map
})()
