from shared.contracts.api_contracts import (
    BoundingBox,
    LayerCatalogResponse,
    LayerDescriptor,
    LayerRenderType,
    LayerSourceType,
    LayerStyleHint,
    MapMode,
    TimeGranularity,
)


def get_layer_catalog() -> LayerCatalogResponse:
    extent = BoundingBox(
        west=109.6,
        south=20.1,
        east=117.4,
        north=25.6,
        crs="EPSG:4326",
    )

    items = [
        LayerDescriptor(
            layer_id="wind-field",
            dataset_key="wind_field_demo",
            display_name="风场",
            description="2D Demo 风场图层，演示时间轴联动、热点更新与前后端协议对接。",
            category="气象场",
            source_type=LayerSourceType.demo,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=True,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            tags=["wind", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="precipitation",
            dataset_key="precipitation_demo",
            display_name="降水",
            description="2D Demo 小时降水图层，后续可映射到 TiTiler、GEE 或融合降水产品。",
            category="灾害监测",
            source_type=LayerSourceType.demo,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="teal-blue", unit_label="mm/h", opacity=0.8),
            tags=["rainfall", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="temperature",
            dataset_key="temperature_demo",
            display_name="温度",
            description="2D Demo 热环境图层，后续可接遥感反演、站点订正与历史栅格。",
            category="热环境",
            source_type=LayerSourceType.demo,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.82),
            tags=["temperature", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="remote-sensing",
            dataset_key="remote_sensing_demo",
            display_name="遥感反演",
            description="2D Demo 遥感反演图层，当前以占位协议演示字段映射与空数据状态。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="purple-green", unit_label="index", opacity=0.75),
            tags=["remote-sensing", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="lab-output",
            dataset_key="lab_output_demo",
            display_name="课题组模型输出",
            description="2D Demo 课题组模型输出图层，模拟任务结果与风险分区产物。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.heatmap,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.day,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="magenta-yellow", unit_label="score", opacity=0.9),
            tags=["model", "2d-demo", "frontend-aligned"],
        ),
    ]

    return LayerCatalogResponse(items=items)
