from app.weatherengine.constants import WEATHER_LAYER_SPECS
from shared.contracts.api_contracts import (
    BoundingBox,
    LayerCapabilities,
    LayerCatalogResponse,
    LayerDescriptor,
    LayerRenderType,
    LayerSourceType,
    LayerStyleHint,
    MapMode,
    TimeGranularity,
)


def _layer_capabilities(
    *,
    render_strategy: str,
    data_domain: str,
    paint_mode: str | None = None,
    primary_metric: str | None = None,
    supports_particle_flow: bool = False,
    supports_map_layer: bool = True,
    supports_viewport_refresh: bool | None = None,
    viewport_refresh_mode: str | None = None,
    legend_ticks: list[float | int | str] | None = None,
    notes: list[str] | None = None,
    delivery_modes: list[str] | None = None,
    result_interfaces: list[str] | None = None,
) -> LayerCapabilities:
    if supports_viewport_refresh is None:
        supports_viewport_refresh = render_strategy in {"weather_tile", "workflow_map_layer"}
    if viewport_refresh_mode is None and supports_viewport_refresh:
        viewport_refresh_mode = "tile" if render_strategy == "weather_tile" else "workflow"
    if delivery_modes is None:
        delivery_modes = ["tile_cache", "point_query"] if render_strategy == "weather_tile" else ["workflow_result"]
    if result_interfaces is None:
        result_interfaces = (
            ["map_layer", "weather_point"]
            if render_strategy == "weather_tile"
            else ["json", "text", "table", "map_layer"]
        )
    return LayerCapabilities(
        render_strategy=render_strategy,
        paint_mode=paint_mode,
        data_domain=data_domain,
        primary_metric=primary_metric,
        supports_particle_flow=supports_particle_flow,
        supports_map_layer=supports_map_layer,
        supports_viewport_refresh=supports_viewport_refresh,
        viewport_refresh_mode=viewport_refresh_mode,
        legend_ticks=legend_ticks or [],
        notes=notes or [],
        delivery_modes=delivery_modes,
        result_interfaces=result_interfaces,
    )


def _weather_capabilities(layer_id: str) -> LayerCapabilities:
    spec = WEATHER_LAYER_SPECS[layer_id]
    return _layer_capabilities(
        render_strategy="weather_tile",
        data_domain="weather",
        paint_mode=spec.paint_mode,
        primary_metric=spec.primary_metric,
        supports_particle_flow=spec.paint_mode == "particle_flow",
        legend_ticks=list(spec.legend_ticks),
        notes=list(spec.notes),
    )


def _workflow_map_capabilities(
    *,
    data_domain: str,
    paint_mode: str | None = None,
    supports_viewport_refresh: bool = True,
    delivery_modes: list[str] | None = None,
    result_interfaces: list[str] | None = None,
) -> LayerCapabilities:
    return _layer_capabilities(
        render_strategy="workflow_map_layer",
        data_domain=data_domain,
        paint_mode=paint_mode,
        supports_viewport_refresh=supports_viewport_refresh,
        delivery_modes=delivery_modes,
        result_interfaces=result_interfaces,
    )


def get_layer_catalog() -> LayerCatalogResponse:
    extent = BoundingBox(
        west=109.6,
        south=20.1,
        east=117.4,
        north=25.6,
        crs="EPSG:4326",
    )
    china_extent = BoundingBox(
        west=73.0, south=15.0, east=137.0, north=59.0, crs="EPSG:4326",
    )
    global_extent = BoundingBox(
        west=-180.0, south=-90.0, east=180.0, north=90.0, crs="EPSG:4326",
    )

    items = [
        LayerDescriptor(
            layer_id="wind-field",
            dataset_key="wind_field",
            display_name="风场（10m）",
            description="10 米高度风场粒子流图层，Open-Meteo 实时数据，支持时间轴联动与热点更新。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=True,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field"),
            tags=["wind", "frontend-aligned", "10m"],
        ),
        LayerDescriptor(
            layer_id="wind-field-80m",
            dataset_key="wind_field_80m",
            display_name="风场（80m）",
            description="80 米高度风场粒子流图层，对应现代风机轮毂高度。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-80m"),
            tags=["wind", "frontend-aligned", "80m", "turbine-hub"],
        ),
        LayerDescriptor(
            layer_id="wind-field-120m",
            dataset_key="wind_field_120m",
            display_name="风场（120m）",
            description="120 米高度风场粒子流图层，大型/海上风机轮毂高度参考层。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-120m"),
            tags=["wind", "frontend-aligned", "120m", "offshore"],
        ),
        LayerDescriptor(
            layer_id="wind-field-180m",
            dataset_key="wind_field_180m",
            display_name="风场（180m）",
            description="180 米高度风场粒子流图层，大气边界层顶部参考风场。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-180m"),
            tags=["wind", "frontend-aligned", "180m", "boundary-layer"],
        ),
        LayerDescriptor(
            layer_id="wind-field-850hPa",
            dataset_key="wind_field_850hpa",
            display_name="风场（850hPa）",
            description="850 hPa 气压层风场粒子流图层（约 1.5 km AGL），低空急流与对流 inflow 参考。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.78),
            capabilities=_weather_capabilities("wind-field-850hPa"),
            tags=["wind", "frontend-aligned", "850hPa", "pressure-level", "low-level-jet"],
        ),
        LayerDescriptor(
            layer_id="wind-field-500hPa",
            dataset_key="wind_field_500hpa",
            display_name="风场（500hPa）",
            description="500 hPa 气压层风场粒子流图层（约 5.5 km AGL），中空天气尺度流场参考。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.74),
            capabilities=_weather_capabilities("wind-field-500hPa"),
            tags=["wind", "frontend-aligned", "500hPa", "pressure-level", "mid-level"],
        ),
        LayerDescriptor(
            layer_id="wind-field-200hPa",
            dataset_key="wind_field_200hpa",
            display_name="风场（200hPa）",
            description="200 hPa 气压层风场粒子流图层（约 12 km AGL），高空急流参考层。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.7),
            capabilities=_weather_capabilities("wind-field-200hPa"),
            tags=["wind", "frontend-aligned", "200hPa", "pressure-level", "upper-jet"],
        ),
        LayerDescriptor(
            layer_id="precipitation",
            dataset_key="precipitation",
            display_name="降水",
            description="小时降水图层，Open-Meteo 实时预报，可映射到 TiTiler、GEE 或融合降水产品。",
            category="灾害监测",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="teal-blue", unit_label="mm/h", opacity=0.8),
            capabilities=_weather_capabilities("precipitation"),
            tags=["rainfall", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="temperature",
            dataset_key="temperature",
            display_name="温度",
            description="2 米气温热环境图层，可接遥感反演、站点订正与历史栅格。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.82),
            capabilities=_weather_capabilities("temperature"),
            tags=["temperature", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="temperature-80m",
            dataset_key="temperature_80m",
            display_name="温度（80m）",
            description="80 米高度温度图层，适用于风机结冰与尾流分析。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-80m"),
            tags=["temperature", "frontend-aligned", "80m", "turbine-hub"],
        ),
        LayerDescriptor(
            layer_id="temperature-120m",
            dataset_key="temperature_120m",
            display_name="温度（120m）",
            description="120 米高度温度图层，大型风机轮毂高度热力参考。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-120m"),
            tags=["temperature", "frontend-aligned", "120m", "offshore"],
        ),
        LayerDescriptor(
            layer_id="temperature-180m",
            dataset_key="temperature_180m",
            display_name="温度（180m）",
            description="180 米高度温度图层，大气边界层顶部热力剖面。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-180m"),
            tags=["temperature", "frontend-aligned", "180m", "boundary-layer"],
        ),
        LayerDescriptor(
            layer_id="pressure",
            dataset_key="pressure",
            display_name="气压",
            description="海平面气压图层，支持等压线分析与低压中心追踪。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="purple-seq", unit_label="hPa", opacity=0.62),
            capabilities=_weather_capabilities("pressure"),
            tags=["pressure", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="humidity",
            dataset_key="humidity",
            display_name="湿度",
            description="2 米相对湿度图层，反映大气水汽含量与体感舒适度。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="green-seq", unit_label="%", opacity=0.66),
            capabilities=_weather_capabilities("humidity"),
            tags=["humidity", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="visibility",
            dataset_key="visibility",
            display_name="能见度",
            description="地面能见度图层，用于航空预警与雾/霾监测。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="amber-gray", unit_label="m", opacity=0.7),
            capabilities=_weather_capabilities("visibility"),
            tags=["visibility", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="ndvi",
            dataset_key="ndvi",
            display_name="植被指数(NDVI)",
            description="归一化植被指数，反映植被覆盖度与生长状况，基于 VIIRS/MODIS 16 天合成 NDVI 反演。",
            category="植被监测",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="ndvi-ramp", unit_label="", opacity=0.78),
            capabilities=_workflow_map_capabilities(data_domain="vegetation", paint_mode="grid_fill"),
            tags=["ndvi", "vegetation", "remote-sensing", "frontend-aligned"],
            module_name="ndvi_daily",
            engine="python_provider",
            default_task_type="ndvi_daily",
            default_data_access_sources={
                "NDVI_16DAY_RASTER": ["NDVI_VIIRS", "NDVI_MODIS", "Soil_Ecological_Data/NDVI/VIIRS", "Soil_Ecological_Data/NDVI/MODIS"],
            },
            run_readiness_summary="待下载 VIIRS/MODIS NDVI 16 天合成产品后可运行。",
            run_readiness_notes=[
                "数据源未就绪：NDVI_VIIRS 和 NDVI_MODIS 候选路径均不存在。",
                "建议放置路径：I:/Geograph_DataSet/Soil_Ecological_Data/NDVI/VIIRS 或 MODIS。",
            ],
        ),
        LayerDescriptor(
            layer_id="remote-sensing",
            dataset_key="remote_sensing",
            display_name="遥感反演",
            description="基于 Sentinel-2 场景的 NDVI 遥感反演工作流，统一走 GEE bridge 自动生成导出 manifest。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="purple-green", unit_label="index", opacity=0.75),
            capabilities=_workflow_map_capabilities(data_domain="remote_sensing", paint_mode="grid_fill"),
            tags=["remote-sensing", "frontend-aligned"],
            engine="gee",
            workflow_id="gee-remote-sensing-ndvi",
            workflow_definition={
                "workflow_id": "gee-remote-sensing-ndvi",
                "nodes": [
                    {
                        "node_id": "source",
                        "node_type": "gee_image",
                        "params": {
                            "asset_id": "COPERNICUS/S2_SR_HARMONIZED/20230101T000000_20230101T000000_T50SMJ",
                        },
                    },
                    {
                        "node_id": "index",
                        "node_type": "gee_spectral_index",
                        "params": {
                            "index": "ndvi",
                            "output_band": "ndvi",
                        },
                    },
                    {
                        "node_id": "export",
                        "node_type": "gee_export_image",
                        "params": {
                            "destination": "manifest",
                            "description": "remote-sensing-ndvi",
                            "file_name_prefix": "remote_sensing_ndvi",
                            "scale": 10,
                            "start_task": False,
                        },
                    },
                ],
                "edges": [
                    {
                        "source_node_id": "source",
                        "source_port": "image",
                        "target_node_id": "index",
                        "target_port": "image",
                    },
                    {
                        "source_node_id": "index",
                        "source_port": "index_image",
                        "target_node_id": "export",
                        "target_port": "image",
                    },
                ],
            },
        ),
        LayerDescriptor(
            layer_id="lab-output",
            dataset_key="smap_omega_cross_analysis",
            display_name="SMAP/Omega 交叉分析（实验）",
            description="实验 provider 链路（lab_output），用于算法联调与验收。生产算法请走 Python provider modules。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.heatmap,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="sample",
            time_granularity=TimeGranularity.day,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="magenta-yellow", unit_label="m³/m³", opacity=0.9),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="heatmap"),
            tags=["sample", "lab-output", "compat"],
            engine="provider",
            run_readiness="ready",
            run_readiness_summary="实验 provider 可运行，结果用于算法联调与验收。",
            run_readiness_notes=[
                "provider_tier=sample；用于兼容旧前端与算法联调。",
                "生产数据请接入 algorithms/providers/Python 模块与真实 data_access 源。",
            ],
        ),
        # ─── 叠加图层（overlay image source）──────────────────────────────────
        LayerDescriptor(
            layer_id="dem-etopo",
            dataset_key="etopo_2022_dem",
            display_name="ETOPO 2022 全球地形",
            description="ETOPO 2022 全球地形起伏数据（60s 分辨率），含陆地高程与海洋深度，terrain 配色。",
            category="遥感产品",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="terrain", unit_label="m", opacity=0.85),
            tags=["dem", "etopo", "topography", "bathymetry", "overlay"],
            run_readiness="ready",
            run_readiness_summary="ETOPO 2022 全球地形数据已就绪。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/DEM/ETOPO_2022/ETOPO_2022_v1_60s_N90W180_surface.tif"],
        ),
        LayerDescriptor(
            layer_id="landcover-cn",
            dataset_key="mcd12q1_landcover_cn",
            display_name="MCD12Q1 土地覆盖",
            description="MODIS MCD12Q1 IGBP 土地覆盖分类，中国区域 0.25° 重采样。",
            category="植被监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="igbp", unit_label="class", opacity=0.8),
            tags=["landcover", "mcd12q1", "igbp", "overlay"],
            run_readiness="ready",
            run_readiness_summary="MCD12Q1 土地覆盖数据已就绪。",
            run_readiness_notes=["数据源: stage2_aligned/landcover_025.mat"],
        ),
        LayerDescriptor(
            layer_id="hfp-cn",
            dataset_key="hfp_2018_cn",
            display_name="人类足迹指数 HFP",
            description="Human Footprint 2018 人类足迹指数，中国区域 0.25° 重采样。",
            category="遥感产品",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="hot", unit_label="score", opacity=0.8),
            tags=["hfp", "human-footprint", "overlay"],
            run_readiness="ready",
            run_readiness_summary="HFP 2018 数据已就绪。",
            run_readiness_notes=["数据源: stage2_aligned/hfp_025.mat"],
        ),
        LayerDescriptor(
            layer_id="aridity-cn",
            dataset_key="aridity_index_cn",
            display_name="干旱指数 AI",
            description="Aridity Index 干旱指数（P/PET），中国区域 0.25°。",
            category="热环境",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="brg", unit_label="AI", opacity=0.8),
            tags=["aridity", "drought", "overlay"],
            run_readiness="ready",
            run_readiness_summary="Aridity Index 数据已就绪。",
            run_readiness_notes=["数据源: stage2_aligned/aridity_025.mat"],
        ),
        LayerDescriptor(
            layer_id="omega-output",
            dataset_key="omega_inversion_smap",
            display_name="Omega 植被光学厚度",
            description="SMAP Omega 植被光学厚度反演结果（全球 EASE-Grid 9km，doy 017 多年均值）。",
            category="模拟结果",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="plasma", unit_label="Omega", opacity=0.75),
            tags=["omega", "inversion", "vod", "overlay"],
            run_readiness="ready",
            run_readiness_summary="Omega 反演结果已就绪。",
            run_readiness_notes=["数据源: InversionResults/smap_avg/doy_017.mat"],
        ),
        LayerDescriptor(
            layer_id="smap-sm-ts",
            dataset_key="smap_sm_timeseries",
            display_name="SMAP 土壤湿度时间序列",
            description="SMAP L3 土壤湿度日数据时间序列（2023 年 1 月，13 天，中国区域），支持时间维度切换。",
            category="热环境",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="sample",
            time_granularity=TimeGranularity.day,
            default_time_offset=0,
            extent=china_extent,
            style=LayerStyleHint(palette="ylgnbu", unit_label="m³/m³", opacity=0.7),
            tags=["smap", "soil-moisture", "time-series", "overlay"],
            run_readiness="ready",
            run_readiness_summary="SMAP 土壤湿度时间序列数据已就绪（13 天）。",
            run_readiness_notes=["数据源: stage1_smap_mat/SMAP_L3_SM_P_*.mat (13 files)"],
        ),
        LayerDescriptor(
            layer_id="gpcp-precip-ts",
            dataset_key="gpcp_precip_timeseries",
            display_name="GPCP 月降水时间序列",
            description="GPCP 月平均降水卫星-雨量计合成产品（V3.2），全球 0.5°，采样 24 个月。",
            category="气象场",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="sample",
            time_granularity=TimeGranularity.month,
            default_time_offset=0,
            extent=global_extent,
            style=LayerStyleHint(palette="blues", unit_label="mm/month", opacity=0.8),
            tags=["gpcp", "precipitation", "time-series", "overlay"],
            run_readiness="ready",
            run_readiness_summary="GPCP 月降水时间序列数据已就绪（24 个月采样）。",
            run_readiness_notes=["数据源: Weather/Precipitation/Precipitation/dataset/GPCPMON_L3_*_V3.2.nc4 (336 files, sampled 24)"],
        ),
        # ─── 新增数据集叠加图层（10 个） ────────────────────────────────────────
        LayerDescriptor(
            layer_id="gebco-dem-cn",
            dataset_key="gebco_2024_dem_cn",
            display_name="GEBCO 2024 海底地形（中国）",
            description="GEBCO 2024 全球海底地形数据，中国区域裁剪，含陆地高程与海洋深度。",
            category="遥感产品",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="terrain", unit_label="m", opacity=0.85),
            tags=["dem", "gebco", "bathymetry", "overlay"],
            run_readiness="ready",
            run_readiness_summary="GEBCO 2024 DEM 中国区域数据已就绪。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/DEM/GEBCO_2024.nc"],
        ),
        LayerDescriptor(
            layer_id="cmfd-precip-cn",
            dataset_key="cmfd_precip_cn",
            display_name="CMFD 中国区域降水",
            description="中国区域高精度格点降水数据集（CMFD），2002 年 1 月月降水。",
            category="气象场",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="ylgnbu", unit_label="mm", opacity=0.8),
            tags=["precipitation", "cmfd", "china", "overlay"],
            run_readiness="ready",
            run_readiness_summary="CMFD 中国区域降水数据已就绪（2002-01）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/Precipitation/pre_2002_01.tif"],
        ),
        LayerDescriptor(
            layer_id="clcd-cn",
            dataset_key="clcd_1997_cn",
            display_name="CLCD 中国土地覆盖",
            description="China Land Cover Dataset (CLCD) 1997 年土地覆盖分类（9 类）。",
            category="植被监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="tab10", unit_label="class", opacity=0.85),
            tags=["landcover", "clcd", "china", "overlay"],
            run_readiness="ready",
            run_readiness_summary="CLCD 1997 土地覆盖数据已就绪。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/LandCover/CLCD_v01_1997.tif"],
        ),
        LayerDescriptor(
            layer_id="biomass-cn",
            dataset_key="esa_biomass_2020_cn",
            display_name="ESA BIOMASS 2020（中国）",
            description="ESA CCI BIOMASS L4 AGB 合并产品 2020 年，中国区域地上生物量。",
            category="植被监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="ylgn", unit_label="Mg/ha", opacity=0.85),
            tags=["biomass", "esa", "agb", "overlay"],
            run_readiness="ready",
            run_readiness_summary="ESA BIOMASS 2020 中国区域数据已就绪。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/Biomass/ESACCI-BIOMASS-L4-AGB-MERGED-100m-2020-fv6.0.nc"],
        ),
        LayerDescriptor(
            layer_id="era5-dwaa-cn",
            dataset_key="era5_dwaa_smci_2020",
            display_name="ERA5 白天热浪事件（2020）",
            description="ERA5 基于 SMCI 指标的白天热浪事件累积计数（2020 全年 366 天）。",
            category="灾害监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="ylorrd", unit_label="events", opacity=0.8),
            tags=["era5", "heatwave", "dwaa", "disaster", "overlay"],
            run_readiness="ready",
            run_readiness_summary="ERA5 DWAA 白天热浪事件数据已就绪（2020）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/Hazards/DWAA_result/DW_T7/ERA5_2020_DW_SMCI.tif"],
        ),
        LayerDescriptor(
            layer_id="era5-wdaa-cn",
            dataset_key="era5_wdaa_smci_2020",
            display_name="ERA5 夜间热浪事件（2020）",
            description="ERA5 基于 SMCI 指标的夜间热浪事件累积计数（2020 全年 366 天）。",
            category="灾害监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=china_extent,
            style=LayerStyleHint(palette="ylgnbu", unit_label="events", opacity=0.8),
            tags=["era5", "heatwave", "wdaa", "disaster", "overlay"],
            run_readiness="ready",
            run_readiness_summary="ERA5 WDAA 夜间热浪事件数据已就绪（2020）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/Hazards/DWAA_result/WD_T7/ERA5_2020_WD_SMCI.tif"],
        ),
        LayerDescriptor(
            layer_id="co2-cn",
            dataset_key="gosat_co2_mean",
            display_name="GOSAT 中层 CO₂ 柱浓度",
            description="GOSAT 卫星中层大气 CO₂ 柱浓度均值产品（MeanCarbonDioxide）。",
            category="大气环境",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="rdylgn_r", unit_label="ppm", opacity=0.8),
            tags=["co2", "gosat", "atmosphere", "overlay"],
            run_readiness="ready",
            run_readiness_summary="GOSAT CO₂ 柱浓度数据已就绪。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/CO2/MidLayerCO2Column/TIF/MeanCarbonDioxide.tif"],
        ),
        LayerDescriptor(
            layer_id="soil-ddca",
            dataset_key="soil_ddca_2015",
            display_name="土壤生态 DDCA",
            description="中国 9km 土壤生态数据集 DDCA 产品（变量 DH，2015-04-01）。",
            category="热环境",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="viridis", unit_label="", opacity=0.8),
            tags=["soil", "ecology", "ddca", "overlay"],
            run_readiness="ready",
            run_readiness_summary="土壤生态 DDCA 数据已就绪（2015-04-01）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/Soil_Ecological_Data/DDCA/DDCA_DH/H/20150401.mat"],
        ),
        LayerDescriptor(
            layer_id="omega-fy-output",
            dataset_key="omega_fy_avg",
            display_name="Omega FY 反演均值",
            description="SMAP Omega 多年均值反演结果（fy_avg 目录，doy 025）。",
            category="模拟结果",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="magma", unit_label="Omega", opacity=0.75),
            tags=["omega", "inversion", "fy", "overlay"],
            run_readiness="ready",
            run_readiness_summary="Omega FY 反演均值数据已就绪（doy 025）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/InversionResults/fy_avg/doy_025.mat"],
        ),
        LayerDescriptor(
            layer_id="forest-ratio",
            dataset_key="forest_ratio_9km_2020",
            display_name="全球森林比例（9km，2020）",
            description="全球 9km 森林比例数据（Forest_Ratio_9KM_2020），值域 0-1。",
            category="植被监测",
            source_type=LayerSourceType.cog,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=False,
            is_realtime=False,
            default_visible=False,
            status="sample",
            extent=global_extent,
            style=LayerStyleHint(palette="ylgn", unit_label="ratio", opacity=0.85),
            tags=["forest", "vegetation", "overlay"],
            run_readiness="ready",
            run_readiness_summary="全球森林比例数据已就绪（2020）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/InversionResults/Forest_Ratio_9KM_2020.mat"],
        ),
        LayerDescriptor(
            layer_id="smap-soil",
            dataset_key="smap_l3",
            display_name="SMAP 土壤湿度",
            description="NASA SMAP L3 土壤湿度反演产品，含 TB 亮温、植被光学厚度(VOD)与 DCA/SCA 反演土壤湿度。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="available",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="soil-moisture-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["smap", "soil-moisture", "remote-sensing", "frontend-aligned"],
            module_name="smap_daily",
            engine="python_provider",
            default_task_type="smap_daily",
            default_data_access_sources={
                "SMAP_SPL3SMP_E": ["SMAP_L3", "smap"],
            },
            run_readiness_summary="SMAP L3 HDF5 数据已就绪（19 个 .h5 文件）。",
            run_readiness_notes=["数据源: I:/Geograph_DataSet/SMAP/SMAP_L3_SM_P_*.h5 (19 files)"],
        ),
        LayerDescriptor(
            layer_id="fy-mwri",
            dataset_key="fy_mwri",
            display_name="FY MWRI 亮温",
            description="风云三号 MWRI 微波成像仪多波段亮温产品(10V/10H/18V/18H/23V/36V/36H/89V/89H)。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="bright-temp-ramp", unit_label="K", opacity=0.78),
            capabilities=_workflow_map_capabilities(data_domain="remote_sensing", paint_mode="grid_fill"),
            tags=["fy", "brightness-temperature", "remote-sensing", "frontend-aligned"],
            module_name="fy_daily",
            engine="python_provider",
            default_task_type="fy_daily",
            default_data_access_sources={
                "FY_MWRI_HDF": ["FY_MWRI_HDF", "Soil_Ecological_Data/FY3B", "Soil_Ecological_Data/FY3D", "Soil_Ecological_Data/FY_MWRI"],
            },
            run_readiness_summary="待下载 FY-3 MWRI 原始 HDF 数据后可运行。",
            run_readiness_notes=[
                "数据源未就绪：FY_MWRI_HDF 候选路径均不存在（需下载 FY-3B/FY-3D MWRI HDF 轨道数据）。",
                "建议放置路径：I:/Geograph_DataSet/Soil_Ecological_Data/FY3B 或 FY3D。",
            ],
        ),
        LayerDescriptor(
            layer_id="station-soil",
            dataset_key="ismn_casmos",
            display_name="站点土壤湿度",
            description="ISMN/CASMOS 站点逐日土壤湿度观测，用于算法验证与产品订正。",
            category="植被监测",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.point,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="station-ramp", unit_label="m³/m³", opacity=0.85),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="point_symbol"),
            tags=["station", "soil-moisture", "validation", "frontend-aligned"],
            module_name="station_daily",
            engine="python_provider",
            default_task_type="station_daily",
            default_data_access_sources={
                "ISMN_STM_OR_CASMOS_TXT": ["ISMN_STATION", "CASMOS_STATION", "Station/ISMN", "Station/CASMOS", "Station/Global_20yr"],
            },
            run_readiness_summary="待下载 ISMN/CASMOS 站点土壤水分数据后可运行。",
            run_readiness_notes=[
                "数据源未就绪：ISMN_STATION 和 CASMOS_STATION 候选路径均不存在。",
                "Station/Global_20yr 含 ISD-Lite 气象站数据，但非土壤水分观测，不可作为替代。",
                "需下载 ISMN STM 格式或 CASMOS TXT 格式的土壤水分站点数据。",
            ],
        ),
        LayerDescriptor(
            layer_id="inversion-daily",
            dataset_key="inversion_daily",
            display_name="单日反演",
            description="单日微波反演产品，含土壤湿度(SM)、植被光学厚度(VOD)与反演诊断量(DH)。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="available",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="inversion-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["inversion", "soil-moisture", "vod", "frontend-aligned"],
            module_name="inversion_daily",
            engine="python_provider",
            default_task_type="inversion_daily",
            default_data_access_sources={
                "daily_bundle_mat": ["daily_bundle_mat", "Soil_Ecological_Data/DDCA/DDCA_DH/H"],
            },
        ),
        LayerDescriptor(
            layer_id="block-inversion",
            dataset_key="block_inversion",
            display_name="块反演",
            description="时间序列块反演产品，含 DH/SM/VOD/Tau_ini 多变量时间序列矩阵。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="available",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="block-inversion-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["block-inversion", "timeseries", "soil-moisture", "vod", "frontend-aligned"],
            module_name="block_inversion",
            engine="python_provider",
            default_task_type="block_inversion",
            default_data_access_sources={
                "timeseries_bundle_mat": ["timeseries_bundle_mat", "INVERSION_OMEGA_SMAP", "INVERSION_OMEGA_FY"],
            },
        ),
        LayerDescriptor(
            layer_id="omega-block",
            dataset_key="omega_block",
            display_name="OMEGA 反演",
            description="OMEGA 算法块反演产品，含 OMEGA/SM_RET/VOD_RET/Tau_star 多变量反演矩阵。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="available",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="omega-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["omega", "retrieval", "soil-moisture", "vod", "frontend-aligned"],
            module_name="omega_block",
            engine="python_provider",
            default_task_type="omega_block",
            default_data_access_sources={
                "timeseries_bundle_mat": ["timeseries_bundle_mat", "INVERSION_OMEGA_SMAP", "INVERSION_OMEGA_FY"],
            },
        ),
    ]

    return LayerCatalogResponse(items=items)


def get_layer_descriptor(layer_id: str) -> LayerDescriptor | None:
    for item in get_layer_catalog().items:
        if item.layer_id == layer_id:
            return item
    return None
