from app.weatherengine.constants import WEATHER_LAYER_SPECS
from shared.contracts.api_contracts import (
    BoundingBox,
    LayerCapabilities,
    LayerCatalogResponse,
    LayerDescriptor,
    LayerRenderType,
    LayerSourceType,
    LayerStyleHint,
    MapMode,
    TimeGranularity,
)


def _layer_capabilities(
    *,
    render_strategy: str,
    data_domain: str,
    paint_mode: str | None = None,
    primary_metric: str | None = None,
    supports_particle_flow: bool = False,
    supports_map_layer: bool = True,
    supports_viewport_refresh: bool | None = None,
    viewport_refresh_mode: str | None = None,
    legend_ticks: list[float | int | str] | None = None,
    notes: list[str] | None = None,
    delivery_modes: list[str] | None = None,
    result_interfaces: list[str] | None = None,
) -> LayerCapabilities:
    if supports_viewport_refresh is None:
        supports_viewport_refresh = render_strategy in {"weather_tile", "workflow_map_layer"}
    if viewport_refresh_mode is None and supports_viewport_refresh:
        viewport_refresh_mode = "tile" if render_strategy == "weather_tile" else "workflow"
    if delivery_modes is None:
        delivery_modes = ["tile_cache", "point_query"] if render_strategy == "weather_tile" else ["workflow_result"]
    if result_interfaces is None:
        result_interfaces = (
            ["map_layer", "weather_point"]
            if render_strategy == "weather_tile"
            else ["json", "text", "table", "map_layer"]
        )
    return LayerCapabilities(
        render_strategy=render_strategy,
        paint_mode=paint_mode,
        data_domain=data_domain,
        primary_metric=primary_metric,
        supports_particle_flow=supports_particle_flow,
        supports_map_layer=supports_map_layer,
        supports_viewport_refresh=supports_viewport_refresh,
        viewport_refresh_mode=viewport_refresh_mode,
        legend_ticks=legend_ticks or [],
        notes=notes or [],
        delivery_modes=delivery_modes,
        result_interfaces=result_interfaces,
    )


def _weather_capabilities(layer_id: str) -> LayerCapabilities:
    spec = WEATHER_LAYER_SPECS[layer_id]
    return _layer_capabilities(
        render_strategy="weather_tile",
        data_domain="weather",
        paint_mode=spec.paint_mode,
        primary_metric=spec.primary_metric,
        supports_particle_flow=spec.paint_mode == "particle_flow",
        legend_ticks=list(spec.legend_ticks),
        notes=list(spec.notes),
    )


def _workflow_map_capabilities(
    *,
    data_domain: str,
    paint_mode: str | None = None,
    supports_viewport_refresh: bool = True,
    delivery_modes: list[str] | None = None,
    result_interfaces: list[str] | None = None,
) -> LayerCapabilities:
    return _layer_capabilities(
        render_strategy="workflow_map_layer",
        data_domain=data_domain,
        paint_mode=paint_mode,
        supports_viewport_refresh=supports_viewport_refresh,
        delivery_modes=delivery_modes,
        result_interfaces=result_interfaces,
    )


def get_layer_catalog() -> LayerCatalogResponse:
    extent = BoundingBox(
        west=109.6,
        south=20.1,
        east=117.4,
        north=25.6,
        crs="EPSG:4326",
    )

    items = [
        LayerDescriptor(
            layer_id="wind-field",
            dataset_key="wind_field_demo",
            display_name="风场（10m）",
            description="10 米高度风场粒子流图层，Open-Meteo 实时数据，演示时间轴联动与热点更新。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=True,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field"),
            tags=["wind", "2d-demo", "frontend-aligned", "10m"],
        ),
        LayerDescriptor(
            layer_id="wind-field-80m",
            dataset_key="wind_field_80m_demo",
            display_name="风场（80m）",
            description="80 米高度风场粒子流图层，对应现代风机轮毂高度。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-80m"),
            tags=["wind", "2d-demo", "frontend-aligned", "80m", "turbine-hub"],
        ),
        LayerDescriptor(
            layer_id="wind-field-120m",
            dataset_key="wind_field_120m_demo",
            display_name="风场（120m）",
            description="120 米高度风场粒子流图层，大型/海上风机轮毂高度参考层。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-120m"),
            tags=["wind", "2d-demo", "frontend-aligned", "120m", "offshore"],
        ),
        LayerDescriptor(
            layer_id="wind-field-180m",
            dataset_key="wind_field_180m_demo",
            display_name="风场（180m）",
            description="180 米高度风场粒子流图层，大气边界层顶部参考风场。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.85),
            capabilities=_weather_capabilities("wind-field-180m"),
            tags=["wind", "2d-demo", "frontend-aligned", "180m", "boundary-layer"],
        ),
        LayerDescriptor(
            layer_id="wind-field-850hPa",
            dataset_key="wind_field_850hpa_demo",
            display_name="风场（850hPa）",
            description="850 hPa 气压层风场粒子流图层（约 1.5 km AGL），低空急流与对流 inflow 参考。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.78),
            capabilities=_weather_capabilities("wind-field-850hPa"),
            tags=["wind", "frontend-aligned", "850hPa", "pressure-level", "low-level-jet"],
        ),
        LayerDescriptor(
            layer_id="wind-field-500hPa",
            dataset_key="wind_field_500hpa_demo",
            display_name="风场（500hPa）",
            description="500 hPa 气压层风场粒子流图层（约 5.5 km AGL），中空天气尺度流场参考。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.74),
            capabilities=_weather_capabilities("wind-field-500hPa"),
            tags=["wind", "frontend-aligned", "500hPa", "pressure-level", "mid-level"],
        ),
        LayerDescriptor(
            layer_id="wind-field-200hPa",
            dataset_key="wind_field_200hpa_demo",
            display_name="风场（200hPa）",
            description="200 hPa 气压层风场粒子流图层（约 12 km AGL），高空急流参考层。",
            category="气象场",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.vector,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="blue-cyan", unit_label="m/s", opacity=0.7),
            capabilities=_weather_capabilities("wind-field-200hPa"),
            tags=["wind", "frontend-aligned", "200hPa", "pressure-level", "upper-jet"],
        ),
        LayerDescriptor(
            layer_id="precipitation",
            dataset_key="precipitation_demo",
            display_name="降水",
            description="2D Demo 小时降水图层，后续可映射到 TiTiler、GEE 或融合降水产品。",
            category="灾害监测",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="teal-blue", unit_label="mm/h", opacity=0.8),
            capabilities=_weather_capabilities("precipitation"),
            tags=["rainfall", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="temperature",
            dataset_key="temperature_demo",
            display_name="温度",
            description="2D Demo 热环境图层，后续可接遥感反演、站点订正与历史栅格。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.82),
            capabilities=_weather_capabilities("temperature"),
            tags=["temperature", "2d-demo", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="temperature-80m",
            dataset_key="temperature_80m_demo",
            display_name="温度（80m）",
            description="80 米高度温度图层，适用于风机结冰与尾流分析。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-80m"),
            tags=["temperature", "frontend-aligned", "80m", "turbine-hub"],
        ),
        LayerDescriptor(
            layer_id="temperature-120m",
            dataset_key="temperature_120m_demo",
            display_name="温度（120m）",
            description="120 米高度温度图层，大型风机轮毂高度热力参考。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-120m"),
            tags=["temperature", "frontend-aligned", "120m", "offshore"],
        ),
        LayerDescriptor(
            layer_id="temperature-180m",
            dataset_key="temperature_180m_demo",
            display_name="温度（180m）",
            description="180 米高度温度图层，大气边界层顶部热力剖面。",
            category="热环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="orange-red", unit_label="degC", opacity=0.58),
            capabilities=_weather_capabilities("temperature-180m"),
            tags=["temperature", "frontend-aligned", "180m", "boundary-layer"],
        ),
        LayerDescriptor(
            layer_id="pressure",
            dataset_key="pressure_demo",
            display_name="气压",
            description="海平面气压图层，支持等压线分析与低压中心追踪。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="purple-seq", unit_label="hPa", opacity=0.62),
            capabilities=_weather_capabilities("pressure"),
            tags=["pressure", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="humidity",
            dataset_key="humidity_demo",
            display_name="湿度",
            description="2 米相对湿度图层，反映大气水汽含量与体感舒适度。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="green-seq", unit_label="%", opacity=0.66),
            capabilities=_weather_capabilities("humidity"),
            tags=["humidity", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="visibility",
            dataset_key="visibility_demo",
            display_name="能见度",
            description="地面能见度图层，用于航空预警与雾/霾监测。",
            category="大气环境",
            source_type=LayerSourceType.weather,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=True,
            default_visible=False,
            time_granularity=TimeGranularity.hour,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="amber-gray", unit_label="m", opacity=0.7),
            capabilities=_weather_capabilities("visibility"),
            tags=["visibility", "atmosphere", "frontend-aligned"],
        ),
        LayerDescriptor(
            layer_id="ndvi",
            dataset_key="ndvi_demo",
            display_name="植被指数(NDVI)",
            description="归一化植被指数，反映植被覆盖度与生长状况，基于 Landsat/Sentinel 遥感反演。",
            category="植被监测",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="ndvi-ramp", unit_label="", opacity=0.78),
            capabilities=_workflow_map_capabilities(data_domain="vegetation", paint_mode="grid_fill"),
            tags=["ndvi", "vegetation", "remote-sensing", "frontend-aligned"],
            module_name="ndvi_daily",
            engine="python_provider",
            default_task_type="ndvi_daily",
            default_data_access_sources={
                "NDVI_16DAY_RASTER": ["NDVI_VIIRS", "NDVI_MODIS", "ndvi"],
            },
        ),
        LayerDescriptor(
            layer_id="remote-sensing",
            dataset_key="remote_sensing_demo",
            display_name="遥感反演",
            description="基于 Sentinel-2 场景的 NDVI 遥感反演工作流，统一走 GEE bridge 自动生成导出 manifest。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="purple-green", unit_label="index", opacity=0.75),
            capabilities=_workflow_map_capabilities(data_domain="remote_sensing", paint_mode="grid_fill"),
            tags=["remote-sensing", "2d-demo", "frontend-aligned"],
            engine="gee",
            workflow_id="gee-remote-sensing-ndvi",
            workflow_definition={
                "workflow_id": "gee-remote-sensing-ndvi",
                "nodes": [
                    {
                        "node_id": "source",
                        "node_type": "gee_image",
                        "params": {
                            "asset_id": "COPERNICUS/S2_SR_HARMONIZED/20230101T000000_20230101T000000_T50SMJ",
                        },
                    },
                    {
                        "node_id": "index",
                        "node_type": "gee_spectral_index",
                        "params": {
                            "index": "ndvi",
                            "output_band": "ndvi",
                        },
                    },
                    {
                        "node_id": "export",
                        "node_type": "gee_export_image",
                        "params": {
                            "destination": "manifest",
                            "description": "remote-sensing-ndvi",
                            "file_name_prefix": "remote_sensing_ndvi",
                            "scale": 10,
                            "start_task": False,
                        },
                    },
                ],
                "edges": [
                    {
                        "source_node_id": "source",
                        "source_port": "image",
                        "target_node_id": "index",
                        "target_port": "image",
                    },
                    {
                        "source_node_id": "index",
                        "source_port": "index_image",
                        "target_node_id": "export",
                        "target_port": "image",
                    },
                ],
            },
        ),
        LayerDescriptor(
            layer_id="lab-output",
            dataset_key="lab_output_demo",
            display_name="课题组模型输出",
            description="课题组样板 provider 输出图层，可运行完整 provider 链路，但当前结果仅用于联调与界面验收。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.heatmap,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="sample",
            time_granularity=TimeGranularity.day,
            default_time_offset=0,
            extent=extent,
            style=LayerStyleHint(palette="magenta-yellow", unit_label="score", opacity=0.9),
            capabilities=_workflow_map_capabilities(data_domain="model_output", paint_mode="heatmap"),
            tags=["model", "sample-provider", "frontend-aligned"],
            engine="provider",
            run_readiness="ready",
            run_readiness_summary="样板 provider 链路，可运行但结果仅用于联调/演示，不代表正式生产数据。",
            run_readiness_notes=["当前图层为样板 provider 输出，适合联调与界面验收，不作为正式业务结果事实源。"],
        ),
        LayerDescriptor(
            layer_id="smap-soil",
            dataset_key="smap_l3",
            display_name="SMAP 土壤湿度",
            description="NASA SMAP L3 土壤湿度反演产品，含 TB 亮温、植被光学厚度(VOD)与 DCA/SCA 反演土壤湿度。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="soil-moisture-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["smap", "soil-moisture", "remote-sensing", "frontend-aligned"],
            module_name="smap_daily",
            engine="python_provider",
            default_task_type="smap_daily",
            default_data_access_sources={
                "SMAP_SPL3SMP_E": ["SMAP_L3", "smap"],
            },
        ),
        LayerDescriptor(
            layer_id="fy-mwri",
            dataset_key="fy_mwri",
            display_name="FY MWRI 亮温",
            description="风云三号 MWRI 微波成像仪多波段亮温产品(10V/10H/18V/18H/23V/36V/36H/89V/89H)。",
            category="遥感产品",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="bright-temp-ramp", unit_label="K", opacity=0.78),
            capabilities=_workflow_map_capabilities(data_domain="remote_sensing", paint_mode="grid_fill"),
            tags=["fy", "brightness-temperature", "remote-sensing", "frontend-aligned"],
            module_name="fy_daily",
            engine="python_provider",
            default_task_type="fy_daily",
            default_data_access_sources={
                "FY_MWRI_HDF": ["fy", "fy_mwri", "FY_MWRI_HDF"],
            },
        ),
        LayerDescriptor(
            layer_id="station-soil",
            dataset_key="ismn_casmos",
            display_name="站点土壤湿度",
            description="ISMN/CASMOS 站点逐日土壤湿度观测，用于算法验证与产品订正。",
            category="植被监测",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.point,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="station-ramp", unit_label="m³/m³", opacity=0.85),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="point_symbol"),
            tags=["station", "soil-moisture", "validation", "frontend-aligned"],
            module_name="station_daily",
            engine="python_provider",
            default_task_type="station_daily",
            default_data_access_sources={
                "ISMN_STM_OR_CASMOS_TXT": ["ISMN_STATION", "CASMOS_STATION", "station/ismn", "station/casmos"],
            },
        ),
        LayerDescriptor(
            layer_id="inversion-daily",
            dataset_key="inversion_daily",
            display_name="单日反演",
            description="单日微波反演产品，含土壤湿度(SM)、植被光学厚度(VOD)与反演诊断量(DH)。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="inversion-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["inversion", "soil-moisture", "vod", "frontend-aligned"],
            module_name="inversion_daily",
            engine="python_provider",
            default_task_type="inversion_daily",
        ),
        LayerDescriptor(
            layer_id="block-inversion",
            dataset_key="block_inversion",
            display_name="块反演",
            description="时间序列块反演产品，含 DH/SM/VOD/Tau_ini 多变量时间序列矩阵。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="block-inversion-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["block-inversion", "timeseries", "soil-moisture", "vod", "frontend-aligned"],
            module_name="block_inversion",
            engine="python_provider",
            default_task_type="block_inversion",
        ),
        LayerDescriptor(
            layer_id="omega-block",
            dataset_key="omega_block",
            display_name="OMEGA 反演",
            description="OMEGA 算法块反演产品，含 OMEGA/SM_RET/VOD_RET/Tau_star 多变量反演矩阵。",
            category="模拟结果",
            source_type=LayerSourceType.algorithm_output,
            render_type=LayerRenderType.raster,
            supported_map_modes=[MapMode.mode_2d],
            supports_time=True,
            is_realtime=False,
            default_visible=False,
            status="placeholder",
            time_granularity=TimeGranularity.day,
            default_time_offset=-1,
            extent=extent,
            style=LayerStyleHint(palette="omega-ramp", unit_label="m³/m³", opacity=0.8),
            capabilities=_workflow_map_capabilities(data_domain="soil_moisture", paint_mode="grid_fill"),
            tags=["omega", "retrieval", "soil-moisture", "vod", "frontend-aligned"],
            module_name="omega_block",
            engine="python_provider",
            default_task_type="omega_block",
        ),
    ]

    return LayerCatalogResponse(items=items)


def get_layer_descriptor(layer_id: str) -> LayerDescriptor | None:
    for item in get_layer_catalog().items:
        if item.layer_id == layer_id:
            return item
    return None
